### ISSUE TITLE
No option for custom characters

### ISSUE THREAD

**Issue by koolache** [profmori/FourSoulsStats#1]
I play my games with a couple custom character cards, such as dr fetus, but theres no support for that. I would say just add the same thing that lets you add custom players to fix it. Also a way to edit/delete past games if you mess up a game would be really nice.

**Comment by profmori** [comment]
Splitting this into 2 issues for readability

**Comment by profmori** [comment]
have added ability to add custom characters and items in the settings menu

Leaving this open as it is still basic, and I hope to add the ability to upload custom art for custom characters

**Comment by profmori** [comment]
This is done and will be included in the next update (which will be big)
